apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    k8s-app: kube-state-metrics
    release: prometheus
    app.kubernetes.io/instance: kube-state-metrics

spec:
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
      release: prometheus
      app.kubernetes.io/instance: kube-state-metrics

  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics

